import { describe, expect, it } from "vitest";
import type { RuntimeRunInput } from "../types.js";
import { TEST_USAGE_CONTEXT } from "./helpers/usageContext.js";
import {
  buildClaudeQueryOptions,
  type ClaudeRuntimeExecutionOptions,
} from "../adapters/claude/options.js";

const baseInput: RuntimeRunInput = {
  runtimeId: "claude",
  providerId: "anthropic",
  prompt: "say OK",
  projectRoot: "/tmp/project",
  cwd: "/tmp/project",
  usageContext: TEST_USAGE_CONTEXT,
};

describe("buildClaudeQueryOptions — settings.attribution normalization", () => {
  it("emits empty settings when execution.settings is undefined", () => {
    const options = buildClaudeQueryOptions(baseInput, {
      // settings intentionally omitted
    } satisfies ClaudeRuntimeExecutionOptions);

    // Must NOT be { attribution: { commit: "", pr: "" } } — empty attribution
    // strings cause Claude Code (>= 2.1.x) to exit with code 1.
    expect(options.settings).toEqual({});
  });

  it("collapses fully-empty attribution into empty settings", () => {
    const options = buildClaudeQueryOptions(baseInput, {
      settings: { attribution: { commit: "", pr: "" } },
    } satisfies ClaudeRuntimeExecutionOptions);

    expect(options.settings).toEqual({});
  });

  it("keeps non-empty commit and drops the empty pr field", () => {
    const options = buildClaudeQueryOptions(baseInput, {
      settings: { attribution: { commit: "Co-Authored-By: bot <noreply@example.com>", pr: "" } },
    } satisfies ClaudeRuntimeExecutionOptions);

    expect(options.settings).toEqual({
      attribution: { commit: "Co-Authored-By: bot <noreply@example.com>" },
    });
    // pr must be absent, never an empty string
    expect((options.settings as { attribution?: { pr?: string } }).attribution?.pr).toBeUndefined();
  });

  it("keeps non-empty pr and drops the empty commit field", () => {
    const options = buildClaudeQueryOptions(baseInput, {
      settings: { attribution: { commit: "   ", pr: "Generated by AIF" } },
    } satisfies ClaudeRuntimeExecutionOptions);

    expect(options.settings).toEqual({ attribution: { pr: "Generated by AIF" } });
    expect(
      (options.settings as { attribution?: { commit?: string } }).attribution?.commit,
    ).toBeUndefined();
  });

  it("passes both non-empty attribution fields through unchanged", () => {
    const options = buildClaudeQueryOptions(baseInput, {
      settings: { attribution: { commit: "commit-trailer", pr: "pr-trailer" } },
    } satisfies ClaudeRuntimeExecutionOptions);

    expect(options.settings).toEqual({
      attribution: { commit: "commit-trailer", pr: "pr-trailer" },
    });
  });
});
